version: '3'
services:
  webapp:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - SECRET_KEY=${SECRET_KEY}
    volumes:
      - flask_session:/app/flask_session

volumes:
  flask_session: